### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by a-haan** [asivery/node-shazam-api#1]
I tested this lib out and couldn't get any success. I successfully convert audio files to pcm as the readme outlines but I get returned value of null on every attempt.

**Comment by asivery** [comment]
@a-haan I have discovered a bug with the current implementation and fixed it, please let me know if it's better now.

**Comment by a-haan** [comment]
Hey @asivery, thanks for the update - I gave it another go but I'm still not getting anything back,

I verified the audio was recorded correctly.

my output:
info 17087064
info Splitting the commandline.
info Reading option '-nostdin' ... matched as option 'stdin' (enable or disable interaction on standard input) with argument 0.
info Reading option '-y' ... matched as option 'y' (overwrite output files) with argument '1'.
info Reading option '-hide_banner' ... matched as option 'hide_banner' (do not show program banner) with argument '1'.
info Reading option '-i' ... matched as input url with argument 'test.webm'.
info Reading option '-ar' ... matched as option 'ar' (set audio sampling rate (in Hz)) with argument '8000'.
info Reading option '-ac' ... matched as option 'ac' (set number of audio channels) with argument '1'.
info Reading option '-f' ... matched as option 'f' (force format) with argument 's16le'.
info Reading option 'test.pcm' ... matched as output url.
info Finished splitting the commandline.
info Parsing a group of options: global .
info Applying option nostdin (enable or disable interaction on standard input) with argument 0.
info Applying option y (overwrite output files) with argument 1.
info Applying option hide_banner (do not show program banner) with argument 1.
info Successfully parsed a group of options.
info Parsing a group of options: input url test.webm.
info Successfully parsed a group of options.
info Opening an input file: test.webm.
info Opening 'test.webm' for reading
info Setting default whitelist 'file,crypto,data'
info Probing matroska,webm score:100 size:2048
info Probing mp3 score:1 size:2048
info Format matroska,webm probed with size=2048 and score=100
info st:0 removing common factor 1000000 from timebase
info Before avformat_find_stream_info() pos: 150 bytes read:32768 seeks:0 nb_streams:1
info All info found
info stream 0: start_time: 0 duration: NOPTS
info format: start_time: 0 duration: NOPTS (estimate from bit rate) bitrate=0 kb/s
info After avformat_find_stream_info() pos: 1419 bytes read:32768 seeks:0 frames:1
info Input #0, matroska,webm, from 'test.webm':
info   Metadata:
info     encoder         : Chrome
info   Duration: N/A, start: 0.000000, bitrate: N/A
info     Stream #0:0(eng), 1, 1/1000: Audio: opus, 48000 Hz, mono, fltp (default)
info Successfully opened the file.
info Parsing a group of options: output url test.pcm.
info Applying option ar (set audio sampling rate (in Hz)) with argument 8000.
info Applying option ac (set number of audio channels) with argument 1.
info Applying option f (force format) with argument s16le.
info Successfully parsed a group of options.
info Opening an output file: test.pcm.
info Setting default whitelist 'file,crypto,data'
info Successfully opened the file.
info Stream mapping:
info   Stream #0:0 -> #0:0 (opus (native) -> pcm_s16le (native))
info cur_dts is invalid st:0 (0) [init:0 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
info detected 10 logical cores
info Setting 'time_base' to value '1/48000'
info Setting 'sample_rate' to value '48000'
info Setting 'sample_fmt' to value 'fltp'
info Setting 'channel_layout' to value '0x4'
info tb:1/48000 samplefmt:fltp samplerate:48000 chlayout:0x4
info Setting 'sample_fmts' to value 's16'
info Setting 'sample_rates' to value '8000'
info Setting 'channel_layouts' to value '0x4'
info auto-inserting filter 'auto_resampler_0' between the filter 'Parsed_anull_0' and the filter 'format_out_0_0'
info query_formats: 4 queried, 6 merged, 3 already done, 0 delayed
info Using fltp internally between filters
info ch:1 chl:mono fmt:fltp r:48000Hz -> ch:1 chl:mono fmt:s16 r:8000Hz
info Output #0, s16le, to 'test.pcm':
info   Metadata:
info     encoder         : Lavf58.45.100
info     Stream #0:0(eng), 0, 1/8000: Audio: pcm_s16le, 8000 Hz, mono, s16, 128 kb/s (default)
info     Metadata:
info       encoder         : Lavc58.91.100 pcm_s16le
info EOF on sink link out_0_0:default.
info No more output streams to write to, finishing.
info size=     108kB time=00:00:06.89 bitrate= 128.0kbits/s speed=27.3x
info video:0kB audio:108kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
info Input file #0 (test.webm):
info   Input stream #0:0 (audio): 115 packets read (110966 bytes); 115 frames decoded (331200 samples);
info   Total: 115 packets (110966 bytes) demuxed
info Output file #0 (test.pcm):
info   Output stream #0:0 (audio): 116 frames encoded (55200 samples); 116 packets muxed (110400 bytes);
info   Total: 116 packets (110400 bytes) muxed
info 115 frames successfully decoded, 0 decoding errors
info Statistics: 0 seeks, 1 writeouts
info Statistics: 111932 bytes read, 0 seeks
info resolve with 0
progress generating
progress generating
progress transmitting
progress generating
send null


my code:

`  const shazam = new Shazam();

    const pcm = fs.readFileSync(
      development ? "./public/test.pcm" : "/tmp/test.pcm",
    );
    const samples = s16LEToSamplesArray(pcm);
    // console.table(samples);
  
  const send = await shazam.recognizeSong(samples, function (progress: any) {
    console.log("progress", progress);
  }
  );
  console.log("send", send);
`

**Comment by asivery** [comment]
@a-haan Can you try with -ar 16000 instead of 8000?

**Comment by a-haan** [comment]
@asivery Amazing, that worked!!!

**Comment by asivery** [comment]
Thanks for the info. I've updated the readme. I'm treating the issue as closed.
