### ISSUE TITLE
How to use with blob/base64 microphone record ?

### ISSUE THREAD

**Issue by cstaelen** [asivery/node-shazam-api#2]
Hello, 

First of all, thank you for your great works ! 

I try to use your lib to identify songs previously recorded with microphone (like official app) in a ReactJS app.
After recording, I have a blob/base64, i tried things like this : 
```js
    const shazam = new Shazam();
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
      bytes[i] = binaryString.charCodeAt(i);
    }
    const samples = s16LEToSamplesArray(bytes);

    const songData = await shazam.recognizeSong(samples, (state: string) => {
      console.log("callback", state);
    });
    console.log("songData", songData);
 ```

"callback" return "generating"  and "transmitting" steps ... searching... and "generating" again before ending with response 
"songData" is null

UPDATE - Here the CURL of the sent request : 

```sh
curl 'https://amp.shazam.com/discovery/v5/en/US/iphone/-/tag/CE620D8F-CCE6-4DB1-9CBD-1E536E230873/A42B8388-9FBD-4ED2-955A-25ED1FED200A?sync=true&webv3=true&sampling=true&connected=&shazamapiversion=v3&sharehub=true&hubv5minorversion=v5.1&hidelb=true&video=v3' \
  -H 'sec-ch-ua: "Not_A Brand";v="8", "Chromium";v="120", "Brave";v="120"' \
  -H 'X-Shazam-AppVersion: 14.1.0' \
  -H 'Accept-Language: en' \
  -H 'X-Shazam-Platform: IPHONE' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36' \
  -H 'Content-Type: application/json' \
  -H 'Accept: */*' \
  -H 'Referer: http://localhost:3000/' \
  -H 'sec-ch-ua-platform: "macOS"' \
  --data-raw '{"timezone":"Europe/Paris","signature":{"uri":"data:audio/vnd.shazam.sig;base64,gCX+ysgH7ccYDAAAAJwRlAAAAAAAAAAAAAAAAAAAABgAAAAAAAAAAJUJAQAAAHwAAAAAQBgMAABAAANgqgAAAAtFdbULEAVyWAkNzHUmCgp8eH4MA9J0SRAhKXNICBFwd84LDOdydAoKrnXPDgcydoIJG3d1gwgDvHX/DyRNdIoOEm12Qgwo13JTCQXVeKwPBoV1hgsC/XeJEARwdQgIA9xzNwwKq3RTDQgPdhQLCgV1iA4Dp3QFCQoGdTIPCOpytwkNSXTkDAnIcw4MJFF14wgBknLyDRg/dj0MAxh2AhAKene/CwWedCkPAABBAANgOgIAAArGc04RASh3bh4Gl3HBJAQIdMohA1VzDCYD3HcKGgI3dtAVBZB39B4E6XU/FgQ7dr4WAANz8CoBWHNMHQExdmglBQh0gxQFsHUeLAbJeJAnCCV09hMBd3UsIwU/c9IsATp2thwHp3RzFQKJdsgQCqF3rBEEpnRjKwW9deUjAjNykSkCoXN7HwUgdW8bAPdzuCYD73RHLgNfdUITAPt2EhgDp3PbIACKdPAkADZz8SsMVXWnGQVMdTMcBvFzGhQEG3aJIgBOdsYtDFxzsykB03aMFwA7dcccB9ZzkRUGjXTKFgMtdWkoBFV1WRoCenM8JQL0dZUfBCl2sSoBo3QwGwm3dVAcALp1qCYFrHNqIQUwcushAbJ0ihIBsnWtLASrdr0cABl0miIDvnShKQLweEgUBXV0ky0EFXYGJALtdcUWCqN2tx4L1nZtJATtc0wfCiZ0wxkAXXeHIwEWd8AmAvl4cCAEunU9KwS8dcMsA/Z29hwBQ3c9FgWxdU0UBbRy9ikBNnb+EAG5eGglCUd1rhMHYXUeFQXWdzcSBJB1Ty4Dw3Z/IAMOdsUdBuh1dRYEb3OPKwP/dcEVA6d1bycFznRREQEKdI0cA8Z0kx8Cy3fDKAdcdP4ZBRl6zSEBTncKJQZ+eOcpAV92piYBlHcPFAlJdhAXAD5zASQIr3Y6KQRIcyUZBHF0UhEBRHV9LQhzdjImB/12XB4BMnMCFgZReEEqCjN2ThgJ33XULAy5dcMbA6t1Iy4COnWaJQAAQgADYL8EAAAKhHS1NQB/cuBmAWtzhj4CvHa9RgE/dcBcAT12xUEAuHTAVQGFdGU4Anl3dU8E/XZ/RwS3c1VfAnN3t0gA4nY7TQHFdXxlAct1l0MD9nbIWwBiduxoAf5xg1IBK3lvLgOKdwVhA6J1gjoD/nNQSwEHc0gvABFzLGYB9HWJawHpdOhvAYJ1hj8Bk3VzOQEYdPkwAXV1QFkEW3aeRAI6dc1RAphzwj4A2HW+ZwHwdJZYBkl1e1QDenWnNgBedLFkB7d2iUgAMXW0XQOucxVOAY10gDwCVXTNRwMWePsyANp20GYBUXTNYQKBdB46AL50BlYAvHd9WgSudnowA5h2OEAAcnVtbQOac440AEZ1mDoD/3UJYAJ0dYtFAHhzQGQBbnTUXAQ5c/E7A5N30WsCSHZbUwF/dHxfBeh1pUwCN3TwWwRZdRdXAU13Nz8A9XTLUAFhdPMzCE13TC8A13TuXgGPcsNOAJJ1jFgAh3SZWwDUdPtpAn10tFEFm3eVaAP6dnNlAqpyQF4BS3Q3WQETdF9IASx0OksDFXj9MgDSdMVuASF0r2EAD3chZwQAd/pCBT91QzwB5HJQbwMkc0Y4AlZ0MjUCOHZtRwDLdiBOA5t0GlsEP3cNSQArd8hkAmB1OlAA1HUqXQFmdQVWAiN0t0wCwXUrUwDZdMlYADd4z2cBI3fROQEedO1eBVt2mkUDoXRmMAK5dMtiASVzxzMBaXTzVgNCdrI3ADp0uDoCGHaaSAGwdBoyADx1ylIAUnWJVQQcd0tgAyJz6zUA3XLYRAGgdBEzAD14vjwBiXbyVwHmcmBNAz12xmkGdnVBSwd9d7ZvAR11K0EBUHY3NAB4dTheArB1YjsEqXRPSQHbdCg+AeR2bk4D6nmkZgFQdndfASd1QFcBGnZJOQNzdRFRBXJ2WlUDZHNCMAC5dKZYAt50sj4DZXYTaQFtduw5A7Zwu1wECXQ+NgDhdfFsA/91fDEE1nVhUAFGe/pJAIh4v20ERnUPZATJc3FCAZZzfj8DinctNAC1dHFjBep1aEABTXf1UQpWdAtTAQ10P18EOHYMbAJvd6kyAQZ1CToAqnfAQwJVd7tnARd2REkBGHPPXgP4cwY/Aadzxi8B3XMJVAG2eJRZBNtzFFEBKnjKOwLCdM5gAat3gEcBg3UETwJpdIFXAdB2dTgGTnMXTQC6c75PBqR2jkQAZ3fWVQacczExAO906DoAAnYtUwVmdvFAAJ12aVsBQ3PZaABzdqVuAnFzRUUBZHSQVAVKdXE0AGp0vWUFg3N7SwEUdoNAAGl2rUYAWnT0VwUEdUpZAAB3N20Bb3TUPgEkdQc4AUB2dGYBGHUHTgT6c5c8AA1yxlECcXSGagGBc0kvArd0vkoCLHPDOQAYdXheAuZ1YDIC9nMIWgDBdT1oAhp1njYATHI2YQG8dC5MBKR1VWsBZHUDQAAMc7dhA+h1LlwE7XTQSAEBd0RkAl52ODABGHVbNQI6dmM9AHR1z1QE+nXZbAHzdARfAYd0m0kCfXQJPwOgd1BCAHd1X1sDyHdOUwOBdl9HAS50o2sBCHelNAIKdbc4ABZ3SVgEEXbLLwEtdQE8APJ1PE8Ej3WvbgIodu5cAhNz2mYAQwADYEcEAAAKBnR2qgI6dE2mAb1yH5UBDnYLjwD7comZA+10cHcEQXYBcgKfdBKcAvR2r4YC53PYfADZcuyrAw55d5MCT3SOjQBHc8OdAj12sXQDwXXyfQEDdlGGAk51r4sCaHnTeQDGc5WoBCd1zIAAJ3bahAIUcxqZAz92LHgAgnODkgErdFSkAs52i6cCTHMqgwI9dQOgAzp2c5cBcHdLfwOueMWtBdN0lIcDdHTacQM6dE+CAWh4u5EDAHSmlgZ9crGIAjd1Ro0GVXPGmQN6dwZ6ASV2N6UBOHNHcwE/dH6QAXl09nYAanYtlgKjdnp9BKt0sHQBf3PEgAMjd2mhAuRyy4IIynbReAGzdWlwAtN1FoYEG3XFpwG6dY2FA0FymncA73O6mAESda6pAhV1iHEAx3OxkQGycoCIAS1zuHUAWXK2lwVAd7WOAql1/58HcXXcogHCdodzAkd19a4DfXatcgL4d6l+Azh4E6EDMnZ4igO6dBl8AFxzsqgDcHj9nAIvdHKsA2RyPHUDzHZrhAEhc8t3Ajl295QE8HNBqgExdZiDAXl4NIwBuXXkmQEJd5elAe52fH0CCXdplANfcz6eA/F2KYkFkXXtlwDEdNmhAIJ2EKUBp3QyegMAc4ubAUp6Qa0CE3bwfwP7dDF0A0h3/6ICJ3MKiAHLc0KFAXZ2uXsDQ3SrmgN7dTJ4ADt2NX8EqnXygAB7dT+dADh3A6gAhXh6rgTIdKaGAml3jqABz3N+nAKZc36NAYV1zZIBA3d7lgCKcQCnAbRzZ4IFG3YrjAJMdBKZAoh1MocBUHbynQORdoZ3ATx3BpoAlXdxpQEtdpBwC2l3/3ICu3QumAkndtSHBKF0VqECXneJgAIpdkd1AMJ0kHwAS3Y6qQV6dbykBRt1La0CJXMNfADlc4enAkR1m5IADnS5nAJsebd2A8tzaI4BKXXDmAJtdYmlAVR1unEBonSLogBKdjavAix2qHkGaHULlQFsdmWBB+Z2A3sBwHTzqwLGdUWoASh1330B5nKQcgFnc+93AzN4u4IAhXb7kwKNd6SLBulz5ogGcHT+dAVzc4yFAA10x6wB+XXZlwEteHZ8AR50KqYBz3T9nwLKdj9zAadzi3cBWHPEkAHid0uXAD5zSKIBPncbmgLYdaV7BBp4wHABeHYCqgBPeIivAVp2+6QBRHZSjACAc8mRB7R2G5sCuHbEiQApc+yNAA11FJ4BLHVwdAQMdk6rAr107HUBTXRqhgTVdWiKAZ908YQBJXd2nwZ/duWmAbd1eoAEY3SirAIddCWDAax0Mp0E2HTohQAedcaOAZNzv6AEe3jCcQHcdTJ4AFV1bX4AC3QyoAIucgavBGx38nsANHbKkQS8ddalAqp2TKoBMHaIiwIgdNmWBlZ0J5EAq3SyqAKNdoZwAXh114EBPni2dAKMc3SiApt0eIYByHQsfwJ4dI18Aolzg4cA","samplems":4009},"timestamp":1706025080004,"context":{},"geolocation":{}}' \
  --compressed
```

Encoding seems fine : 
<img width="961" alt="Capture d’écran 2024-01-23 à 16 53 21" src="https://github.com/asivery/node-shazam-api/assets/5319804/5251a1ad-0a33-48b0-956b-9d2ef50ba68e">

Any idea how to achieve that ? 

Thank you for your help 🙏

**Comment by asivery** [comment]
Hello @cstaelen!
First of all - what is your method of recording audio? The base64 string you're passing to atob() might not be the correct format. If you could please attach your incoming base64 here for me to test it'd be great.
If you're getting something like a WAV file, you might need to use ffmpeg.wasm to convert the audio, before passing it to s16LEToSamplesArray.

**Comment by asivery** [comment]
See example [here](https://github.com/asivery/webminidisc/blob/0877bfbffccd16dc9e1986e3d3a303b8d82c88bf/src/redux/actions.ts#L1171) - this is also a react app, which (among a lot of other things) does just that - use this library to identify audio recorded via the microphone (or other sources).

**Comment by cstaelen** [comment]
Hi @asivery, thank you for you fast answer ! 

I'm using [capacitor-voice-recorder](https://github.com/tchvu3/capacitor-voice-recorder/blob/70ee739fe78523593bc512fb015d8d3007651618/src/VoiceRecorderImpl.ts#L129C38-L129C51) which uses JS MediaRecorder API and it returns base64 converted audio blob [here](https://github.com/tchvu3/capacitor-voice-recorder/blob/70ee739fe78523593bc512fb015d8d3007651618/src/VoiceRecorderImpl.ts#L163)

Thanks for the link ! I will investigate this way. It seems pretty similar indeed 👍

**Comment by asivery** [comment]
No problem! Also, to use this in the browser, you need a way to bypass CORS. For that project, I f.ex load a userscript.

**Comment by cstaelen** [comment]
Hi @asivery ! Thank you for you help ! I just make it works like a charm 👌 

I've got just one last request for you if you please 🙏 
Is it possible to add a boolean parameters, something like :
`const response = await shazam.recognizeSong(samples, completeResponse);` 
to return complete track object ? 

IMO, it will make your lib much more interesting 😉 

I can propose you a pull request if you prefer !

**Comment by a-haan** [comment]
> Hi @asivery ! Thank you for you help ! I just make it works like a charm 👌
> 
> I've got just one last request for you if you please 🙏 Is it possible to add a boolean parameters, something like : `const response = await shazam.recognizeSong(samples, completeResponse);` to return complete track object ?
> 
> IMO, it will make your lib much more interesting 😉
> 
> I can propose you a pull request if you prefer !

I've already patched the lib with this type of response.  It would be usefull to get the full response from shazam but also an option to send shazam a song name and receive back metadata.

**Comment by asivery** [comment]
@a-haan @cstaelen Do you think https://github.com/asivery/node-shazam-api/commit/c4363bcae52d828a3a4164e44c2d679dd95fbeed will do?

I don't know how to query Shazam with the song name - @a-haan if you know how to do it, a pull request would be quite nice :)

**Comment by a-haan** [comment]
> @a-haan @cstaelen Do you think [c4363bc](https://github.com/asivery/node-shazam-api/commit/c4363bcae52d828a3a4164e44c2d679dd95fbeed) will do?
> 
> I don't know how to query Shazam with the song name - @a-haan if you know how to do it, a pull request would be quite nice :)

Thank you @asivery, this looks perfect. great work!

side note, have you tried this library on vercel? it works perfectly locally but then seems to crash on vercel or netlify.

**Comment by asivery** [comment]
@a-haan I haven't tried it on any services like that unfortunately, but I think I might know why what you mentioned is happening - often services like Shazam ban the whole IP ranges of datacenters. So most likely that's what's happening here.

**Comment by a-haan** [comment]
> @a-haan I haven't tried it on any services like that unfortunately, but I think I might know why what you mentioned is happening - often services like Shazam ban the whole IP ranges of datacenters. So most likely that's what's happening here.

I fixed the issue, it was an error on my part!

Thank you!

**Comment by asivery** [comment]
Glad I could help :)

**Comment by cstaelen** [comment]
> @a-haan @cstaelen Do you think [c4363bc](https://github.com/asivery/node-shazam-api/commit/c4363bcae52d828a3a4164e44c2d679dd95fbeed) will do?
> 
> I don't know how to query Shazam with the song name - @a-haan if you know how to do it, a pull request would be quite nice :)

It's perfect 👍 
great job @asivery 
Thanks !

**Comment by a-haan** [comment]
> how to query Shazam with the song name - @a-haan if you know how to do it, a pull request would be quite nice :)

It's difficult with no official documentation. I know its possible, there are many rapidapi endpoints that acheive this.  I will keep digging :)
